### ISSUE TITLE
Unable to write values to pp_table

### ISSUE THREAD

**Issue by tictooc** [sibradzic/upp#1]
Everything works except for writing values to the pp_table
Error:
`WARNING: Nothing was written to '/home/test/ppTables/pp_table'. Add --write option to commit the changes for real!`

**Comment by sibradzic** [comment]
@tictooc, sorry for the obvious question, but have you actually tried `--write` option when using `set` command?

**Comment by sibradzic** [comment]
closing this, confirmed that write works when `--write` parameter is used properly.
