### ISSUE TITLE
wrong output format of some offsets

### ISSUE THREAD

**Issue by psyborg55** [sibradzic/upp#11]
MMDependencyTable and probably SclkDependencyTable provide VddcOffset and VddgfxOffset as unsigned int while the actual value is signed int + 1, e.g. CD FF -> 65485 -> -51+1=-50mV

very good table parser btw, it helped me figure out few unneeded BIOS edits

**Comment by sibradzic** [comment]
Are you absolutely sure these are signed? I'm asking because **upp** is decoding everything according to PowerPlasy table definitions in Linux kernel, and these values are clearly defined as **unsigned int** all over the place. Anyway, if you are 200% sure (can you please point me to some reference or doc explaining these values), I guess I could apply this patch:
```
diff --git a/src/upp/decode.py b/src/upp/decode.py
index 1c60e36..6d4f297 100644
--- a/src/upp/decode.py
+++ b/src/upp/decode.py
@@ -463,6 +463,10 @@ def build_data_tree(data, raw=None, decoded=None, parent_name='/',
                 if name in ['a', 'b', 'c', 'm'] and ctyp_cls == ctypes.c_uint:
                     d_symbol = 'f'
                     d_value = struct.unpack(d_symbol, d_bytes)[0]
+                # Defined as uint in kernel, but some report these as signed?
+                elif name in ['VddcOffset', 'VddgfxOffset']:
+                    d_symbol = 'h'
+                    d_value = struct.unpack(d_symbol, d_bytes)[0]
                 if rawdump:
                     _print_raw_value(d_offset, d_symbol, d_bytes,
                                      name, d_value)
```

**Comment by psyborg55** [comment]
here's one example: https://www.overclock.net/photopost/data/1624301/0/05/055c6a60_pwpminvddcatmaxramMMtableoffsets.png
just read the last paragraph in that screenshot

also a dump from other similar tools: https://pastebin.com/uWh6WLmh see line 309

**Comment by sibradzic** [comment]
> here's one example: https://www.overclock.net/photopost/data/1624301/0/05/055c6a60_pwpminvddcatmaxramMMtableoffsets.png
> just read the last paragraph in that screenshot

Yeah, I believe I've seen that thing long time ago, when my understanding of PP tables was quite limited. Don't get me wrong, but some stuff claimed on overclock.net can be very questionable. Any other sources?

> also a dump from other similar tools: https://pastebin.com/uWh6WLmh see line 309

Similar tools? That pastebin output is from earlier revision of **upp**, where data structures have been maintained manually. The values of `VddcOffset` and `VddcGfxOffset` *were* decoded as signed int before https://github.com/sibradzic/upp/commit/70e20fff9bc7b35a6494c29bcc3fe8887b83ea44. The main reason I did that change is to bring that manually-defined data-structures in line with the Linux kernel definitions, I thought those negative values were mistakes, but I ain't sure anymore.

Does setting these to negative values on your RX560 really lower the voltages as reported by the driver?

**Comment by psyborg55** [comment]
since this is mobile chipset it's a bit hard to verify these (most voltages i tried to change made no difference, but i do remember setting one gfxoffset value somewhere in BIOS made a difference) sensor outputs only VDDC and VDDCI values and with VDDCI changing it took me quite some time to figure out i can tweak it in VOI only (0.775V-0.912V range).
anyway i'll try to reproduce this again.

i've read two different explanations about this: one as posted above and another that these are actually negative steps of voltage controller so the actual offset is (from the above example) -50x6.25mV (6.25mV being a controller step)

**Comment by sibradzic** [comment]
hi @psyborg55, any update?

**Comment by psyborg55** [comment]
couldn't reproduce this on mobile rx560 (first time it actually caused bsod and restart but i guess that was due to other changes in bios, whenever some critical parameter change windows restarts before it takes new value in registry) possibly because AVSF enabled but more likely because these tuning capabilities have been removed from bios.

however, this was already confirmed by other with desktop cards, just read posts on this page:
https://www.overclock.net/forum/67-amd/1604567-polaris-bios-editing-rx5xx-rx4xx-515.html

**Comment by sibradzic** [comment]
OK, I'm only half-convinced after reading about **Merutsu**'s experience @ overclock.net. What I would really like to hear is you actually experiencing the effect of setting negative voltage offsets, i.e. you actually seeing the resulting voltages going down for the expected amount.
You say you can't really test due to existing VBIOS mods causing unexpected impact when you touch offsets, but how about this: use **upp** to write your default VBIOS to `/sys/class/drm/cardX/device/pp_table` and then just modify the offsets in question?
You can use **upp** to actually extract an original **pp_table** from original VBIOS, see `extract` option.

**Comment by psyborg55** [comment]
i don't think i can confirm this as i don't experience voltage spikes when watching video or working with OBS studio. vcore voltage remains as i've set it or has only small spikes -+50mV due to AVFS or some other similar scaling technique

**Comment by sibradzic** [comment]
https://github.com/sibradzic/upp/tree/apu-experimental contains the patch to treat `VddcOffset` and `VddcGfxOffset` as signed int.

**Comment by sibradzic** [comment]
@psyborg55 does the apu-experimental branch fix you issue?

**Comment by psyborg55** [comment]
i think it can be considered as fixed. 
e.g. VddgfxOffset: -101 (output differs 1mV from actual value)

**Comment by sibradzic** [comment]
> e.g. VddgfxOffset: -101 (output differs 1mV from actual value)

As this IS the actual value in PP tables, and as I've said before; the purpose of upp is not to interpret the values but just to decode and encode them correctly, so I'll consider this as sufficient.
