### ISSUE TITLE
Is it possible to replace pp_table completely?

### ISSUE THREAD

**Issue by Shished** [sibradzic/upp#13]
Is it possible to replace the loaded pp_table with the one from othe card's VBIOS? Or at least modify all default values with values from the extracted pp_table with a single command? Can `upp` be used for that or some other tool should be used instead?

**Comment by sibradzic** [comment]
Sure thing, you can use **upp**'s `extract` option against some card's VBIOS, and than simply copy that extracted PP table to `/sys/class/drm/card0/device/pp_table` (assuming `card0` is your target card).
But better be careful here, make sure the both cards are of same ASIC & generation, and that you are not putting power limits & voltages to some far extremes.
Perhaps the safest way would be to `extract` the VBIOS, `dump` the extracted values to one text file, and then `dump` your card's values to another file, and finally use something like [meld](https://meldmerge.org/) to check the differences on your own. This way you'll know exactly what is going to be changed...

**Comment by Shished** [comment]
I want to use pp table from from MSI Evoke 5700XT and my GPU is MSI 5700 Evoke GP OC.
Both cards uses same cooling solution and pp_tables are equilval ecept for frequencies and voltages.

[diff.txt](https://github.com/sibradzic/upp/files/4878981/diff.txt)

**Comment by sibradzic** [comment]
Can't tell much from non unified diff, but you should be able to change everything on your 5700 Evoke other than `golden_pp_id` & `golden_revision` to achieve same voltages/clocks/fantargettemp/fanlimitrpm/curve as 5700XT Evoke, with one-liner `upp`.

**Comment by Shished** [comment]
I just tried to copy the pp_table and it is not worth it. Better to change frequencies and voltages manually. Fan curve is way too aggressive  and voltage is too high. OD_VDDC_CURVE leve 2 was like 1202 mV and 2069 Mhz.

**Comment by sibradzic** [comment]
Right, make sense, but anyway, here is the "one liner" I was talking about, feel free to adjust it to your needs:
```
sudo -E env "PATH=$PATH" upp set        \
  power_saving_clock/max/0=2100         \
  overdrive_table/max/0=2150            \
  overdrive_table/max/1=2150            \
  overdrive_table/max/2=2150            \
  overdrive_table/max/4=2150            \
  overdrive_table/max/6=2150            \
  overdrive_table/max/8=950             \
  overdrive_table/max/9=20              \
  overdrive_table/min/3=750             \
  overdrive_table/min/5=750             \
  overdrive_table/min/7=750             \
  smc_pptable/SocketPowerLimitAc/0=200  \
  smc_pptable/SocketPowerLimitDc/0=200  \
  smc_pptable/TdcLimitGfx=184           \
  smc_pptable/MinVoltageUlvGfx=2900     \
  smc_pptable/MinVoltageUlvSoc=2900     \
  smc_pptable/MinVoltageGfx=3000        \
  smc_pptable/MinVoltageSoc=3000        \
  smc_pptable/FreqTableGfx/1=2100       \
  smc_pptable/DcModeMaxFreq/0=2100      \
  smc_pptable/Mp0DpmVoltage/0=3000      \
  smc_pptable/Mp0DpmVoltage/1=3000      \
  smc_pptable/FanAcousticLimitRpm=2000  \
  smc_pptable/FanTargetTemperature=75   \
  smc_pptable/dBtcGbGfxDfll/c=-0.07874  \
  --write
```

**Comment by Shished** [comment]
Which parameter changes the voltages in OD_VDDC_CURVE?

**Comment by sibradzic** [comment]
Min and max clocks & voltages should affect all curves, as well as those quadratic values (but I only see `smc_pptable/dBtcGbGfxDfll/c` being changed here). Try to eliminate some of the parameters and see what affects your curve the most.
