### ISSUE TITLE
Ubuntu 18.04.4 driver version 19.30-934563 Invalid Header length

### ISSUE THREAD

**Issue by PNixx** [sibradzic/upp#14]
Ubuntu 18.04.4 
driver version 19.30-934563
RX 5700 XT
```
$ sudo -E env "PATH=$PATH" upp -p /sys/class/drm/card1/device/pp_table dump
ERROR: Header length (1674) diffes from file length (4095). Is this a valid PowerPlay table?
Traceback (most recent call last):
  File "/home/nixx/.local/bin/upp", line 11, in <module>
    sys.exit(main())
  File "/home/nixx/.local/lib/python3.6/site-packages/upp/upp.py", line 301, in main
    cli(obj={})()
  File "/home/nixx/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/nixx/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/nixx/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nixx/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nixx/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/nixx/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nixx/.local/lib/python3.6/site-packages/upp/upp.py", line 164, in dump
    decode.dump_pp_table(pp_file, rawdump=raw, debug=debug)
  File "/home/nixx/.local/lib/python3.6/site-packages/upp/decode.py", line 573, in dump_pp_table
    for member in data_dict:
TypeError: 'NoneType' object is not iterable
```
For driver 20.20-1089974 work correctly

**Comment by sibradzic** [comment]
Thanks for report @PNixx. Can you please share your `/sys/class/drm/card1/device/pp_table` and more details about your 5700XT model?

**Comment by PNixx** [comment]
[19.30.pp_table.zip](https://github.com/sibradzic/upp/files/5005514/19.30.pp_table.zip)
```
$ uname -a
Linux f2 5.0.0-58-generic #62~18.04.1-Ubuntu SMP Tue Jul 14 03:37:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```
My video card MSI 5700 XT Evoke OC

**Comment by sibradzic** [comment]
By the look of that `19.30.pp_table` you sent, it is likely that driver had somehow messed up the `/sys/class/drm/card1/device/pp_table`, likely on creation. The `pp_file` includes not only PwoerPlay table but also the GDDR timings part of the VROM!
Anyways, check it out, this should work:
```
head --bytes=1674 /sys/class/drm/card1/device/pp_table dump | sudo -E env "PATH=$PATH" upp -p /dev/stdin dump
```

**Comment by PNixx** [comment]
How I can modify table? If I try `sudo -E env "PATH=$PATH" upp set *** --write` I see same error.

**Comment by sibradzic** [comment]
```
head --bytes=1674 /sys/class/drm/card1/device/pp_table > /tmp/pp_table
sudo -E env "PATH=$PATH" upp -p /tmp/pp_table set BLABLA
sudo cp /tmp/pp_table > /sys/class/drm/card1/device/
```

**Comment by PNixx** [comment]
I think, we need replace only first 1674 bytes.

**Comment by PNixx** [comment]
I replace `pp_table`, but after that the hashrate became 38Mh/s instead of 55Mh/s. The voltage settings were applied.

**Comment by PNixx** [comment]
I try concate head and end file, but I see same result: 38mh/s.
```
$ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_head bs=1674 count=1
$ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_end bs=1674 skip=1
$ sudo -E env "PATH=$PATH" upp -p /tmp/pp_table set **** --write
$ sudo bash -c 'cat /tmp/pp_head /tmp/pp_end > /sys/class/drm/card1/device/pp_table'
cat: write error: Invalid argument
```

**Comment by PNixx** [comment]
I try concate head and end file without editing, I same result: 38mh/s:
```
$ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_head bs=1674 count=1
$ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_end bs=1674 skip=1
$ sudo bash -c 'cat /tmp/pp_head /tmp/pp_end > /sys/class/drm/card1/device/pp_table'
cat: write error: Invalid argument
```
What am I doing wrong?

**Comment by PNixx** [comment]
Can you fix and edit only 1674 of file?

**Comment by sibradzic** [comment]
> I try concate head and end file without editing, I same result: 38mh/s:
> 
> ```
> $ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_head bs=1674 count=1
> $ dd if=/sys/class/drm/card1/device/pp_table of=/tmp/pp_end bs=1674 skip=1
> $ sudo bash -c 'cat /tmp/pp_head /tmp/pp_end > /sys/class/drm/card1/device/pp_table'
> cat: write error: Invalid argument
> ```
> 
> What am I doing wrong?

Probably nothing, this looks like some driver issue or some special sauce resulting in tweaking GDDR timings...
BTW, are the md5sum of both `/tmp/pp_end` (after concate) and `/sys/class/drm/card1/device/pp_table` (before replace attempt) the same?

**Comment by sibradzic** [comment]
> Can you fix and edit only first 1674 bytes of file?
What do you mean exactly?

**Comment by PNixx** [comment]
amdmemorytweak not working with GDDR6.

**Comment by PNixx** [comment]
```
$ cat /sys/class/drm/card1/device/pp_table > /tmp/pp_table
$ cat /tmp/pp_table > /sys/class/drm/card0/device/pp_table
cat: write error: Error input/output
```
I think file locked for editing...
I use Install command driver:
```
~/amdgpu-pro-19.30-934563-ubuntu-18.04/amdgpu-pro-install -y --opencl=pal,legacy --headless
```

**Comment by sibradzic** [comment]
`$ cat /tmp/pp_table > /sys/class/drm/card0/device/pp_table`. Careful, this is `card0`.
Also, only root can replace `pp_table`.

**Comment by PNixx** [comment]
Yes, I mistake. Not changing example commands. I copy from and to with root.

**Comment by PNixx** [comment]
19.50-967956 not working, only 20.+

**Comment by sibradzic** [comment]
Provided that `pp_table` has valid data (table length decoded from PowerPlay == file data length), **upp** will work as expected. Even with the invalid and/or unexpected data in `pp_table` *upp* will work, but you have to decouple the PowerPlay data into some temp file, and then modify it in whatever ways you wish.
I don't think that **upp** should workaround this very weird case in its code base, as you could do this with some minimal shell gymnastics. So, I don't see this as an *upp* issue at all, and will close this issue.
