### ISSUE TITLE
Attach pp_table to ROM

### ISSUE THREAD

**Issue by PNixx** [sibradzic/upp#15]
If we can extract pp_table from bios rom, then can we attach pp_table to bios rom?
That would be a great idea. As Red BIOS Editor does for Windows, but MorePowerTool is extremely limited in parameters.

**Comment by sibradzic** [comment]
Sorry, I missed this issue somehow. What do you mean exactly, like replacing the PowerPlay table in VROM with modified one?

**Comment by PNixx** [comment]
Yes. I want extract pp_table from VROM `upp --pp-file=extracted.pp_table extract -r VIDEO.rom`, modify it and attach (replace) in to VROM file. And flash a new bios my card. Is it possible? Under Linux, I have not seen such functionality.

**Comment by sibradzic** [comment]
It should be possible, but don't forget that a new checksum for such modified vBIOS image will have to be calculated and updated. I could work on this, but I have 0 idea where tihs vBIOS checksum is located.
Would be much appreciated if someone can point to some info or example code on how is this done.

**Comment by datspike** [comment]
https://github.com/AnorakTech/Anoraks-AMD-VBIOS-CRC-checker
Here's a VB .NET example on checking a vbios checksum

**Comment by sibradzic** [comment]
OMG, that code :scream: 

But don't worry, I had it figured out few weeks ago, it is super simple: https://github.com/sibradzic/upp/blob/master/src/upp/decode.py#L127-L135 I'll look into implementing it in the following days...

**Comment by psyborg55** [comment]
there is already an app that can fix checksum: https://github.com/jfoster/AMDVBIOSChecksumTool
