### ISSUE TITLE
Parameter for card

### ISSUE THREAD

**Issue by stylesuxx** [sibradzic/upp#18]
My card ist not at ID 0, so `/sys/class/drm/card0/device/pp_table` does not exist but `/sys/class/drm/card1/device/pp_table` does . It would be great if one could pass the approriate ID in order to read the pp_table.

**Comment by azeam** [comment]
You can specify the file to be setting "--pp-file" or just "-p" `upp --pp-file /sys/class/drm/card1/device/pp_table dump`

**Comment by stylesuxx** [comment]
Thank you, not sure how I missed that...
