### ISSUE TITLE
powerplay table default location is not always card0

### ISSUE THREAD

**Issue by harakiru** [sibradzic/upp#22]
As the title suggests the powerplay table isnt in the /sys/class/drm/card0/device/pp_table directory all of the time. Some setups, such as my laptop which has the graphics card connected via an egpu adapter, has this file in /card1/ instead. Therefore the program fails to run since it cant find the file when i tell it to dump it.

**Comment by sibradzic** [comment]
RTFM:
```
-p, --pp-file <filename>        Input/output PP table file.
```
