### ISSUE TITLE
Mem clock and F clock on the 6800 XT

### ISSUE THREAD

**Issue by LiveITA** [sibradzic/upp#24]
Hi, i'm not a great coder and I'm kinda confused on how to use this tool.
I've been using  `upp -p /sys/class/drm/card2/device/pp_table set smc_pptable/FreqTableFclk/0=1940 --write` to set me F clock higher on my GPU. The problem I have is that my memory OC goes from 1075 (1074) to 1000 when I use this command and reforcing the Mem clock to 1075 (1074) does not work.
Soo to fix that I've used 
`upp -p /sys/class/drm/card2/device/pp_table set smc_pptable/FreqTableUclk/3=1075 --write` and it looks like it works by looking at amd-info, but that's actually not true.
The Mem Clock goes to 1075 but the F clock reverts to some low values that I can't even read as I see my F clock as being 1041

This is how my working GPU looks like
![image](https://user-images.githubusercontent.com/22427467/139363423-8ea3622e-f124-4c64-804d-e1e749757a52.png)

This is the one that keeps failing
![image](https://user-images.githubusercontent.com/22427467/139363469-25a2501d-00db-44ca-a9b2-847a58243c18.png)

As you can see my Fclock state reverts to 0
How can I take it back to state 1? 

Here's the BIOS and the MPT file from the GPU, made in windows from the bios downloaded on linux.
[TAM-VEGA6800-1-RadeonRX6800XT-16G-Samsung_GDDR6-113-1E4392U-O5H.zip](https://github.com/sibradzic/upp/files/7438347/TAM-VEGA6800-1-RadeonRX6800XT-16G-Samsung_GDDR6-113-1E4392U-O5H.zip)

**Comment by sibradzic** [comment]
ping?
