### ISSUE TITLE
Ubuntu 20.04 Server - Installation procedure of upp?

### ISSUE THREAD

**Issue by blackmennewstyle** [sibradzic/upp#27]
Sorry for the newbie question but how do i install your piece of software on GNU/Linux Ubuntu 20.04?

**Comment by sibradzic** [comment]
Normally, by doing `pip3 install --user upp`

**Comment by blackmennewstyle** [comment]
> Normally, by doing `pip3 install --user upp`

My bad, i did not realized it was a custom python package when i wrote my question, i actually knew how to do that. I think i might need some sleep.

Actually you can directly perform `sudo pip3 install`, that way you will be able to use it with all users, i am using it with some bash script, which is executed by the `root` user.

Your piece of software works pretty well.

Enjoy your weekend and keep it up the great job :)
