### ISSUE TITLE
can you Add BC250 support

### ISSUE THREAD

**Issue by Tradition2** [sibradzic/upp#28]
is it possible to add BC250 Support 
those use navi gpus but they are ps5 chips

**Comment by sibradzic** [comment]
@Tradition2

Details please, what's BC250? APU?

**Comment by Tradition2** [comment]
![image](https://user-images.githubusercontent.com/32690039/164468492-53020c1e-a25e-48a9-8a5f-ebc648a2432e.png)
this lol its a navi based apu

**Comment by sibradzic** [comment]
Hmm, runtime update of APU PowerPlay table is not supported by kernel driver / SMU firmware...
Does that thing work in Linux at all? If so, can you share the content of `/sys/class/drm/card0/device/pp_table`?
Does it have a video ROM you can extract?

**Comment by Tradition2** [comment]
yeah its only linux based 
i only have a full bios
as for the pp_table i cant open 
[P3.00.AMD.zip](https://github.com/sibradzic/upp/files/8543223/P3.00.AMD.zip)
s

**Comment by sibradzic** [comment]
Can't tell you much without checking Video ROM or `/sys/class/drm/card0/device/pp_table`, but considering this is an APU, it is very likely never going to be supported.

**Comment by sibradzic** [comment]
ping?
