### ISSUE TITLE
Module vbios has no atribute HardLimitTable_v1.

### ISSUE THREAD

**Issue by Haxk20** [sibradzic/upp#3]
I tried to use this script but i always get this message when i do so. Only way to get something is with --raw and that fails when it hits HardLimitTable_v1.
Im using Acer Nitro 5 with RX560X.
I wanted to use this script since the vbios does not set OD limits.

` 0x003d Recursive dive into HardLimitTable v1 @ 0x02cb
Traceback (most recent call last):
  File "upp.py", line 183, in <module>
    cli(obj={})()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "upp.py", line 96, in dump
    decode.decode_pp_table(input_file, debug=True)
  File "/home/haxk20/Data/upp/decode.py", line 205, in decode_pp_table
    off, debug)
  File "/home/haxk20/Data/upp/decode.py", line 204, in decode_pp_table
    decode_pp_table(None, getattr(vbios, table_name), data,
AttributeError: module 'vbios' has no attribute 'HardLimitTable_v1'`

**Comment by sibradzic** [comment]
Hi, thank you for reporting this. Can you please extract and share your video BIOS?

**Comment by Haxk20** [comment]
> Hi, thank you for reporting this. Can you please extract and share your video BIOS?

Hi, Could please tell me how to do that ? Im on Arch Linux and this is laptop.

**Comment by sibradzic** [comment]
Try this:
```
CARD_ID=1
CARD_ROM="/sys/class/drm/card${CARD_ID}/device/rom"
FILE_ROM="vbios${CARD_ID}.bin"
echo 1 > $CARD_ROM
cat $CARD_ROM > $FILE_ROM
echo 0 > $CARD_ROM
echo "Saved as ${FILE_ROM}"
```
Note that `CARD_ID` may be 0 or 1,  I assume 1 because RX560 is likely a secondary VGA in your system, feel free to try both. Also, ROM may be visible through debugfs, check `/sys/kernel/debug/dri1/amdgpu_vbios` (or 0 instead of 1).

**Comment by Haxk20** [comment]
Will do once I get back from work

**Comment by Haxk20** [comment]
Well OK im happy that im finally home. I must say roller skating home from  work in huge rain isnt fun. But anyways. Here is the VBIOS from /sys/kernel/debug.
[vbios_RX560X.zip](https://github.com/sibradzic/upp/files/3478969/vbios_RX560X.zip)
ZIP because of github.

**Comment by sibradzic** [comment]
@Haxk20 thanks for the VBIOS dump. Let me know if it works for you now.

**Comment by Haxk20** [comment]
> @Haxk20 thanks for the VBIOS dump. Let me know if it works for you now.

Indeed it does. Thanks.
