### ISSUE TITLE
Memory Overclock doesnt work as intended

### ISSUE THREAD

**Issue by Celldfusion** [sibradzic/upp#30]
Hello, when i set an overclock on the vram past 1000 mhz on the dpm state 3, it revert back to the past frecuency of the dpm state behind (2). I am using PowerUPP (gui) to achieve that. Everything else works as intended.
GPU: rx 6800 xt asus rog lc
System: manjaro kde 21.2.6
using amdgpu-pro drivers from AUR repository

**Comment by sibradzic** [comment]
Sounds like one of the driver or SMU/PMU quirks. Does the same happen with latest sable kernel driver?

**Comment by sibradzic** [comment]
@Celldfusion ping?
