### ISSUE TITLE
Applying any settings on 6900XT causes a crash

### ISSUE THREAD

**Issue by codebam** [sibradzic/upp#32]
Applying any settings to my 6900XT, such as the same power limit and tdp as what was already set, causes graphics to become unresponsive and crash, requiring a hard reboot.

```
upp -d set --write \
    smc_pptable/SocketPowerLimitAc/0=303 \
    smc_pptable/SocketPowerLimitDc/0=272 \
    smc_pptable/TdcLimit/0=320 \
    smc_pptable/TdcLimit/1=55
```

**Comment by sibradzic** [comment]
Normally, driver crashes are clear indicator of a driver and sometimes firmware issues, upp does nothing other than changing some values in the table. it is the driver that interprets these changes and tells PMU firmware what to do. Can you isolate a particular value change that is causing crash?

Also, kernel, driver and GPU firmware versions? Dmesg output on crash?

**Comment by sibradzic** [comment]
Judging by
```
[  115.878745] amdgpu 0000:0b:00.0: amdgpu: use vbios provided pptable
[  120.478046] amdgpu 0000:0b:00.0: amdgpu: SMU: I'm not done with your previous command: SMN_C2PMSG_66:0x00000006 SMN_C2PMSG_82:0x00000000
[  120.478049] amdgpu 0000:0b:00.0: amdgpu: Failed to enable requested dpm features!
[  120.478050] amdgpu 0000:0b:00.0: amdgpu: Failed to setup smc hw!
[  120.478051] amdgpu 0000:0b:00.0: amdgpu: smu reset failed, ret = -62
```
The upp replaced the table successfully, but SMU got stuck for ~5s applying the change. Ultimately, that crashed the GPU:

```
[  126.397379] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=3054, emitted seq=3056
[  126.397655] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process kwin_wayland pid 2157 thread kwin_wayla:cs0 pid 2191
[  126.397914] amdgpu 0000:0b:00.0: amdgpu: GPU reset begin!
[  126.398414] ------------[ cut here ]------------
[  126.398416] amdgpu 0000:0b:00.0: SMU uninitialized but power ungate requested for 6!
[  126.398450] WARNING: CPU: 2 PID: 590 at drivers/gpu/drm/amd/amdgpu/../pm/swsmu/amdgpu_smu.c:224 smu_dpm_set_power_gate+0x188/0x1a0 [amdgpu]
```

Likely to be a driver or SMU firmware issue. Not much I can do to fix this, if you feel adventurous please report a kernel bug or look for similar ones already reported.

**Comment by codebam** [comment]
> Does it ever crash on 1st attempt after cold-boot?

Doesn't appear to, no

> Have you tried longer intervals between runs, like, say, 30s?

I tried 1 or 2 minutes but it still crashed on the 2nd run

---

I see okay. Thank you

**Comment by Kodehawa** [comment]
> Does it ever crash on 1st attempt after cold-boot? Have you tried longer intervals between runs, like, say, 30s? Are you running any other apps or tools that are modifying the amdgpu power states?

Kind of replying to a closed issue, but for me it crashes no matter when. Trying to apply an upp table even right after booting will result on a black screen for me, with a similar error message.
