### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Satori-Nori** [sibradzic/upp#36]
@sibradzic
Greetings Mr. Samir,

I hope you and your family are fine and safe,

And my apologies for the inconvenience,

I am seeking a dump of power play table in human readable form for AMD RDNA2 card specifically one of RX 6000 Series,

Is it possible for your kind person to provide one or help in providing one as unfortunately I do not have one at the meantime and I need this dump for research purpose,

Also is it possible to generate a dump of power play table in human readable form from a vbios image?

Your early reply is highly appreciated,

You may have a good day and please stay safe and healthy,

Regards.

**Comment by sibradzic** [comment]
> I am seeking a dump of power play table in human readable form for AMD RDNA2 card specifically one of RX 6000

Just any RX6000?

> Also is it possible to generate a dump of power play table in human readable form from a vbios image?

Yes you can do it easily by yourself, TechPowerUp maintains a collection VBIOS images for all kinds of cards, for example https://www.techpowerup.com/vgabios/?model=RX+6800+XT, one only needs to do something like this:

```
wget https://www.techpowerup.com/vgabios/230803/AMD.RX6800XT.16384.201007.rom
pip3 install --user upp
upp extract -r AMD.RX6800XT.16384.201007.rom
upp -p AMD.RX6800XT.16384.201007.rom.pp_table dump
```

Note that voltage values found in the RX6000 series dump outputs are a quadruple of a millivolt, for example:
```
upp -p AMD.RX6800XT.16384.201007.rom.pp_table get smc_pptable/MaxVoltageGfx
4600
```
Meaning that this value actually represents 4600/4 = 1150 millivolts, or 1.15V

**Comment by Satori-Nori** [comment]
@sibradzic

Thank you very much for your kind and quick and informative reply, 

I am glad that the power play table dump in readable human form can be done this way without the need for the presence of the hardware,

Regarding the voltages, as a bios engineer, in fact unofficial one, the voltages min_max range values are indeed in quadruple form, many thanks for highlighting this,

Your support is much appreciated and my gratitude for making such wonderful tool,

I wish you and your family to live healthy, happy, peaceful and stable flourishing life,

Best regards.
