### ISSUE TITLE
Running in scripts or systemd service

### ISSUE THREAD

**Issue by Onslivion** [sibradzic/upp#37]
I’ve tried running upp set to /sys/class/drm/cardX/device/pp_table without anything special. Works just fine

However, when executing my overclocking script (requires me using sudo sh -c “<script>”) or allowing my systemd service to run the script, whenever upp tries to set it returns an error;
````
smc_pptable/MinVoltageGfx=3120 smc_pptable/MaxVoltageGfx=3120
Changing smc_pptable.MinVoltageGfx from 3094 to 3120 at 0x3a6
Changing smc_pptable.MaxVoltageGfx from 4600 to 3120 at 0x3aa
Commiting changes to '/sys/class/drm/card8/device/pp_table'.
Traceback (most recent call last):
  File "/usr/local/bin/upp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/upp/upp.py", line 387, in main
    cli(obj={})()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/upp/upp.py", line 368, in set
    decode._write_binary_file(pp_file, pp_bytes)
  File "/usr/local/lib/python3.8/dist-packages/upp/decode.py", line 52, in _write_binary_file
    f.close()
OSError: [Errno 62] Timer expired
````

Oddly, executing the script without doing sudo (sh -c “<script>”) works, but the rest of my script needs to be run elevated. Been working on this for a bit, and am willing to test out stuff.

this is using amdgpu 22.20.1,
Ubuntu 20.04 w/ kernel 5.15.0-43-generic

**Comment by sibradzic** [comment]
Hi @Onslivion thanks for reporting.

An interesting issue, but it probably has nothing to do with **upp** itself. First, what is exactly the way **upp** is being invoked by systemd? Pasting a service file in here may help...

Next, how did you install upp? Using PIP, local setup.py or something else?

**Comment by Onslivion** [comment]
UPP is installed using apt. The systemd service calls the script for execution at startup

**Comment by sibradzic** [comment]
OK, did you install it with PIP as a local user (`--user` option) as a system wide package? Pasting both service file as well as the script might help understanding what's going on.

**Comment by Onslivion** [comment]
I installed it system wide (sudo pip3 install upp)

I’ll get back to you on the script and service. Service is pretty simple, since it’s just running the script.

**Comment by Onslivion** [comment]
Here is the service;
````
[Unit]
Description=Auto-Tuning Service
After=nvidia-persistenced.service gdm.service
Requires=nvidia-persistenced.service

[Service]
Type=oneshot
Restart=on-failure
ExecStart=/home/onslivion/prototype_kaspa_artemis.sh

[Install]
RequiredBy=kaspa_miner.service kaspa_amd_miner.service
````


Here is a portion of the script where bash gets involved. I shaved off other cards to avoid wasting space; it is effectively the same operations done on each card.
````
INDEX="$((`lspci | grep -i VGA | wc -l`-1))"
for i in $(seq 0 ${INDEX});
do
    args=""
    TEMP_DIR="/sys/class/drm/card${i}/device"
    case $(cat $TEMP_DIR/subsystem_device) in
        0x2413) # 6600
           echo "6600"
           cclk=1650
           gfx_vddc=780
           soc_vddc=775
           vddci=650
           mvdd=1100

           echo "s 1 ${cclk}" > "${TEMP_DIR}/pp_od_clk_voltage"
           echo "c" > "${TEMP_DIR}/pp_od_clk_voltage"
           echo 2 > "${TEMP_DIR}/pp_dpm_sclk"
           echo 0 > "${TEMP_DIR}/pp_dpm_mclk"

           #
           gfx_vddc=$((${gfx_vddc} * 4))
           soc_vddc=$((${soc_vddc} * 4))
           vddci=$((${vddci} * 4))
           mvdd=$((${mvdd} * 4))
           args+="smc_pptable/MinVoltageGfx=${gfx_vddc} "
           args+="smc_pptable/MaxVoltageGfx=${gfx_vddc} "
           args+="smc_pptable/MinVoltageSoc=${soc_vddc} "
           args+="smc_pptable/MaxVoltageSoc=${soc_vddc} "
           args+="smc_pptable/MinVoltageUlvSoc=$((${soc_vddc} - 100)) "
           args+="smc_pptable/MemVddciVoltage/1=${vddci} smc_pptable/MemVddciVoltage/2=${vddci} smc_pptable/MemVddciVoltage/3=${vddci} "
           args+="smc_pptable/MemMvddVoltage/1=${mvdd} smc_pptable/MemMvddVoltage/2=${mvdd} smc_pptable/MemMvddVoltage/3=${mvdd} "

           upp -p $TEMP_DIR/pp_table set ${args} --write
           ;;
    esac
done
````

**Comment by Onslivion** [comment]
So after some testing and discussion with a few others, I was able to alter pp tables using upp set.

Trying to copy the pp_table, edit it, then copy it back would cause the same "Timer expired" issue, but with cp. So definitely not a upp issue.

For some reason, it required me switching to a different profile on the card;
`echo "profile_peak" > /sys/class/drm/cardX/device/power_dpm_force_performance_level`
before I could successfully apply the pp_table.
