### ISSUE TITLE
6800XT changing UCLK locks SCLK to 500Mhz

### ISSUE THREAD

**Issue by DiabeticCrab** [sibradzic/upp#38]
I tried to increase the max and applied mclk of my card (ref. edition, by default it's 1075 Mhz) like this:
```
upp --pp-file=/sys/class/drm/card0/device/pp_table set --write \
overdrive_table/max/6=1100 \
overdrive_table/max/7=1100 \
smc_pptable/FreqTableUclk/3=1100
```

The memory clock does get applied under load, but SCLK is now stuck at 500Mhz. pp_od_clk_voltage lists this: 
```
OD_SCLK:
0: 500Mhz
1: 2444Mhz
```

When I then use upp to restore the default values:
```
upp --pp-file=/sys/class/drm/card0/device/pp_table set --write \
overdrive_table/max/6=1075 \
overdrive_table/max/7=1075 \
smc_pptable/FreqTableUclk/3=1000
```

SCLK is still stuck at 500Mhz, but additionally pp_od_clk_voltage OD_SCLK/1 also lists 500Mhz as the max. possible value now:
```
OD_SCLK:
0: 500Mhz
1: 500Mhz
```
When I set the default values with upp, the sha256 sums of the unmodified and the "modified" pp_tables DO match.

Do you have any idea on how to circumvent this behavior and force the card into behaving properly? I assume that the driver may be doing funky stuff (kernel 6.1.0).

**Comment by sibradzic** [comment]
Hi @DiabeticCrab 
Please see #25, seems to be related.

> When I then use upp to restore the default values ... SCLK is still stuck at 500Mhz.
> When I set the default values with upp, the sha256 sums of the unmodified and the "modified" pp_tables DO match
> I assume that the driver may be doing funky stuff (kernel 6.1.0).

Doing certain changes in pp_table can totally screw the driver power/clock/voltage management, and just reverting the pp_table to default normally does not "unscrew" it (more often than no it makes it even worse). This is all about driver, by no means **upp**'s fault. From what I've seen, problems like these happen more often with non-mainline or amdgpu-pro drivers, especially if built again not so recent kernels, but sometimes even new mainline kernel release screw things up...
Try experimenting with more conservative values, or applying one change at a time and see how it goes and if you can isolate which particular value change makes the driver go nuts.

**Comment by DiabeticCrab** [comment]
So I've been digging a bit and reading through parts of the amdgpu driver code. Compared to GCN it seems like clockspeed control, overdrive and applying pp_tables is handled by the SMU firmware since RDNA2.

When setting a pp_table or using the overdrive controls, the driver does minimal input and value range checking, puts the data into the buffer and calls the SMU with a message which then copies the data over to a private VRAM area, probably performs some more checks and then applies it.

The behaviour I've been seeing likely is the card entering some kind of "safe mode" aka an artificial lockdown :(

For anyone interested in looking further into the matter or experimenting, I'll leave my findings here. I have not tested lifting value range restrictions and relaxing checks within the driver yet, so there may be a chance to get this working.
Here's what the call chain looks like for RX6800 and RX 69X0 series from a file level perspective:

- Higher up portions of the driver ->
- amd/pm/swsmu/amdgpu_smu.c -> 
- amd/pm/swsmu/smu11/sienna_cichlid_ppt.c -> 
- (amd/pm/swsmu/smu11/smu_v11_0.c -> amd/pm/swsmu/smu_cmn.c) || 
- amd/pm/swsmu/smu_cmn.c

Relevant function names:

**amdgpu_smu.c**
(Sets up SCPM handling (PSP verified pp_table). It seems like this could be turned off for RDNA2, since the functionality was added to the driver later during the product life. RDNA3 likely demands this to be on at all times.)

- smu_smc_hw_setup

**sienna_cichlid_ppt.c**

- sienna_cichlid_od_edit_dpm_table (!)
- sienna_cichlid_set_default_od_settings
- sienna_cichlid_od_setting_change_range (!)
- sienna_cichlid_patch_pptable_quirk (this function may be an easy entry point for a patch…)

**smu_v11_0.c**

- smu_v11_0_set_soft_freq_limited_range
- smu_v11_0_set_hard_freq_limited_range
- smu_v11_0_set_single_dpm_table
- smu_v11_0_set_power_limit

**smu_cmn.c**

- smu_cmn_update_table
- smu_cmn_write_pptable

Here is a rough overview where data structure definitions can be found:

- amd/pm/swsmu/inc/smu_v11_0_7_pptable.h (smu_11_0_7_overdrive_table, smu_11_0_7_powerplay_table)
- amd/pm/swsmu/inc/amdgpu_smu.h (smu_table, smu_table_context)
- amd/pm/swsmu/inc/pmfw_if/smu11_driver_if_sienna_cichlid.h (OverdriveTable_t, OverDriveTableExternal_t, PPTable_t, SMU Answers)
- amd/pm/swsmu/inc/pmfw_if/smu_v11_0_7_ppsmc.h (SMU Messages)
