### ISSUE TITLE
"SocClockDependencyTable" in "SocClock" does not look right.

### ISSUE THREAD

**Issue by KCCat** [sibradzic/upp#4]
HI.
I am using  PowerColor Radeon RX Vega 56.
"SocClockDependencyTable" in "SocClock" does not look right.

In /sys/class/drm/card0/device/pp_dpm_socclk
https://pastebin.com/fTDf0J0d

In upp dump
https://pastebin.com/wBF18aSK
https://pastebin.com/jH25VBs5

`cat /sys/class/drm/card0/device/pp_table`
https://transfer.sh/loTm0/pp_table

Thank you very much for this project.

**Comment by sibradzic** [comment]
@KCCat thanks for providing pp_table, let me know if this fixes the issue for you.

Note that, for affected data structures, `Clock` now becomes `ulClk`, and `VddIndex` becomes `ucVddInd`.
