### ISSUE TITLE
I don't have `drm/card0` but `drm/card1` sysfs entry. `upp` fails on that. Please add an option to specify the card to use.

### ISSUE THREAD

**Issue by dreirund** [sibradzic/upp#43]
Ahoj,  
I have no `/sys/class/drm/card0/`, but it is named `/sys/class/drm/card1/` on my machine:

`upp dump`:  
```
[...]
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/pp_table'
```  
`ls -l /sys/class/drm/card1/device/pp_table`:  
```
-rw-r--r-- 1 root root 4096 Apr 28 12:30 /sys/class/drm/card1/device/pp_table
```

Please add an option that allows to specify the card (i.e. `upp -c <number>`, where `<number>` corresponds to the number in `/sys/class/drm/card<number>/`) to use.

Regards!

**Comment by sibradzic** [comment]
You already have option to specify that:
```
 . . .

Options:
  -p, --pp-file <filename>        Input/output PP table binary file.
```
