### ISSUE TITLE
Small oops in decode.py get_value()

### ISSUE THREAD

**Issue by thomab** [sibradzic/upp#6]
The bug causes an inaccurate error message to be printed.

For example:

    $ upp get smcPPTable/SocketPowerLimitDc/3
    0
    $ upp get smcPPTable/SocketPowerLimitDc/4
    ERROR: Invalid parameter "4", avaliable ones are: 0, 1, 2  # <-- should be 0, 1, 2, 3

On line 277 in decode.py:
`indices = [str(i) for i in range(len(data)-1)]`

should instead be:
`indices = [str(i) for i in range(len(data))]`

Regards.

Btw, thanks for putting this program together, great for tuning my navi blower card!

**Comment by sibradzic** [comment]
thanks for reporting @thomab !
